### ISSUE TITLE
Результаты проверки

### ISSUE THREAD

**Issue by EricRovell** [col3name/cinema#1]
# Результаты проверки

## Страница списка фильмов

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [x] Работает переход по клику на фильм(либо на всю карточку, либо на название или постер)
- [x] Реализованы все ограничения и шаблоны ввода для фильтров(там где указаны)
- [ ] Реализованы ограничения на кол-во билетов

## Фильтры

- [x] Фильтрация работает - значения в списке фильтруются

## Страница фильма

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [ ] Реализованы ограничения на кол-во билетов

## Страница заказа

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [x] Финальное кол-во билетов считается корректно
- [ ] Модально окно работает как описано

## Страница о нас

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [x]  Static (страница генериться на билде, а не на реквесте)

## Страница вопросы/ответы

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [x] Static (страница генериться на билде, а не на реквесте)

## Шапка

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [ ] Позиционируется липко(стики)

## Футер

- [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

## Модалка

- [ ] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [ ] Используется портал

## Стор

- [x] Данные корректно разбиты на модули(пример - кинотеатры, фильмы, отзывы, авторы отзывов, корзина)
- [x] Селекторы написаны оптимально(нет кучи дублирования)
- [x] Данные грузятся только по необходимости(отзывы не надо грузить на странице списка фильмов и тд), если уже загружены, то повторно не загружаются.

## Оптимизация

- [x] При изменении кол-ва билетов не перерендеривается вся карточка фильма(в списке фильмов, на странице фильма, в заказе), а только часть с количеством
- [ ] Для картинок используется Image некста. Постеры(про список фильма), которые вне вьюпорта грузятся лениво
- [x] На полях фильтрации с свободным вводом есть debounce(фильтрация происходит только после окончания ввода)

**Comment by EricRovell** [comment]
Вычитал балл с пунктов, от общего количества требований в разделе. Например, в оптимизации не выполнен 1 из 3, вычитаем 1/3. Итого, выходит 8 баллов.

**Comment by EricRovell** [comment]
Есть нюанс, не совсем относящийся к заданию. У меня неправильно отработал тёмный режим, стили будто перемешались. Помогло исправить ситуацию в `devtools` - вкладка `Rendering` - `prefers-color-theme: light`.

**Comment by col3name** [comment]
Ограничение на кол-во билетов реализовано,  макс 30 на фильм

https://github.com/col3name/hw-react/blob/48cae4dc28287f2ce6ec5a973ca2ca30b99d6e53/front/src/redux/store/features/cartSlice.ts#L10
